# **Macro Economic Data Analysis Project**

## Purpose

* The purpose of this project is to move beyond staic data and reporting. By applying the principles from Brent Dykes' Effective Data Storytelling,this analysis transforms complex Kaggle GDP datasets into a clear narrative that identifies economic 'Heroes' and 'Villand'- highlighting the countries that showed the most resilience during global shocks.

## Inputs

*The dataset is from the Kaggle website and is titled "Economic Indicators & Inflation"

## Outputs

* I will initially view the dataset and filter the countiries to only include the UK, USA, Germany and France. I will add an index so that growth rates can be identified. This is to enable better comparisons between the various countries and makes for better data storytelling.

## Additional Comments

* If you have any additional comments that don't fit in the previous bullets, please state them here.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\rayaf\\Documents\\Macro_analysis\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\rayaf\\Documents\\Macro_analysis'

### Raw Data Examination

Checking for anomalies & Selecting Countries for Analysis

In [5]:
import pandas as pd

In [6]:
econ_raw = pd.read_csv(r"C:\Users\rayaf\Documents\Macro_analysis\data\raw_data\Economic Indicators And Inflation.csv")
econ_raw.head()

,Country,Year,GDP (in billion USD),Inflation Rate (%),Unemployment Rate (%),Economic Growth (%)
0,USA,2010,15000.0,1.64,9.63,2.55
1,USA,2011,15500.0,3.16,8.94,1.53
2,USA,2012,16000.0,2.07,8.10,2.28
3,USA,2013,16500.0,1.50,7.70,1.84
4,USA,2014,17000.0,1.62,7.25,2.53

---

In [ ]:
econ_raw.columns = econ_raw.columns.str.strip() # Remove leading and trailing whitespace from column names

In [ ]:
countries = ['UK', 'USA', 'Germany', 'France'] # List of countries to filter

econ_raw = econ_raw[econ_raw['Country'].isin(countries)].copy() 

econ_raw = econ_raw.sort_values(['Country', 'Year']) 

econ_raw['GDP_Index'] = (
    econ_raw.groupby('Country')['GDP (in billion USD)'] 
    .transform(lambda x: (x / x.iloc[0]) * 100) #
    .round(1)
) # Calculate the GDP index for each country by dividing each year's GDP by the first year's GDP and multiplying by 100, then round to one decimal place

### Filtering Countries UK, USA, Germany, and France & Adding Index

In [ ]:
econ_raw.head() # Display the first few rows of the cleaned DataFrame to verify the changes.

,Country,Year,GDP (in billion USD),Inflation Rate (%),Unemployment Rate (%),Economic Growth (%),GDP_Index
144,France,2010,2400.0,1.5,9.5,1.7,100.0
145,France,2011,2500.0,2.3,9.8,1.1,104.2
146,France,2012,2600.0,2.0,10.0,0.0,108.3
147,France,2013,2700.0,0.9,10.3,-0.2,112.5
148,France,2014,2800.0,0.3,10.5,0.2,116.7

### Checking Dataset for Anomolies

In [ ]:
econ_raw.describe() # Get summary statistics for the dataset to understand the distribution of the data and identify any potential outliers or anomalies.

,Year,GDP (in billion USD),Inflation Rate (%),Unemployment Rate (%),Economic Growth (%),GDP_Index
count,64.000000,64.00000,64.000000,64.000000,64.000000,64.000000
mean,2017.500000,7225.00000,2.500625,6.175313,1.925000,128.267187
std,4.646214,6831.06815,1.885198,2.316310,2.641612,18.333715
min,2010.000000,2200.00000,0.000000,3.000000,-9.800000,100.000000
25%,2013.750000,3075.00000,1.257500,4.175000,1.522500,113.100000
50%,2017.500000,3650.00000,2.000000,5.500000,2.415000,127.300000
75%,2021.250000,7350.00000,3.350000,8.025000,2.900000,141.875000
max,2025.000000,22500.00000,8.000000,10.500000,7.400000,168.200000

In [ ]:
econ_raw.info() # Check the data types of each column and look for any potential issues with the data

<class 'pandas.core.frame.DataFrame'>
Index: 64 entries, 144 to 15
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Country                64 non-null     object
 1   Year                   64 non-null     int64
 2   GDP (in billion USD)   64 non-null     float64
 3   Inflation Rate (%)     64 non-null     float64
 4   Unemployment Rate (%)  64 non-null     float64
 5   Economic Growth (%)    64 non-null     float64
 6   GDP_Index              64 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 4.0+ KB

In [ ]:
econ_raw.isnull().sum() # Check for missing values in each column

Country                  0
Year                     0
GDP (in billion USD)     0
Inflation Rate (%)       0
Unemployment Rate (%)    0
Economic Growth (%)      0
GDP_Index                0
dtype: int64

In [ ]:
econ_raw.shape # to check the number of rows and columns in the dataset.

(64, 7)

In [ ]:
econ_raw.columns # Identifying the columns in the dataset.

Index(['Country', 'Year', 'GDP (in billion USD)', 'Inflation Rate (%)',
       'Unemployment Rate (%)', 'Economic Growth (%)', 'GDP_Index'],
      dtype='object')

In [ ]:
econ_raw['Country'].value_counts() # checking to see if the dataset is clean and balanced.

Country
France     16
Germany    16
UK         16
USA        16
Name: count, dtype: int64

---

### Saving Filtered & Indexed Dataset

In [ ]:
econ_raw.to_csv(
    r"C:\Users\rayaf\Documents\Macro_analysis\data\cleaned_data\macro_data.csv",
    index=False
) # Save the cleaned DataFrame to a new CSV file without the index column

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [4]:
import os

try:
    os.makedirs("data/raw", exist_ok=True)
except Exception as e:
    print(e)